version: '3.8'

services:

  mongodb:
    build: ./database
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - ./database/data:/data/files

  api:
    build: .
    depends_on:
      - mongodb
    env_file: .env
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
      - '/app/.venv'
